<s> ::= <def_angle>:<def_depth>:<def_stepsize>:<def_colour1>:<def_colour2>:<def_circle_angle>:<def_axiom>:<rules>
<def_angle> ::= angle=<angle>
<def_depth> ::= depth=<depth>
<def_stepsize> ::= stepsize=<stepsize>
<def_colour1> ::= colour1=<n> <n> <n>
<def_colour2> ::= colour2=<n> <n> <n>
<def_circle_angle> ::= circle_angle=<angle>
<def_axiom> ::= axiom=<code><code>
<rules> ::= <rule> | <rules>:<rule>
<rule> ::= <char>=<rhs>
<code> ::= <char> | <char><code>
<rhs> ::= <code> | {<code>} | [<code>]
# <char> ::= f | F | { | } | [ | ] | - | + | C | S | s | X | A | D | a | n | m | N | M
<char> ::= f | F | - | + | C | D | FD | n | m | N | M
<angle> ::= 15 | 25 | 60
<depth> ::=  2 | 3 | 4 | 5
<stepsize> ::= 10 | 16
<n> ::= 0 | 20 | 40 | 60 | 80 | 100 | 120 | 140 | 160 | 180 | 200 | 220 | 240 | 256
